# Generated by Django 5.1.1 on 2024-10-25 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='RFC',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RFC debe tener 13 caracteres.', regex='^.{13}$')]),
        ),
    ]
