# Generated by Django 5.1.2 on 2024-11-04 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_rfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('ubicacion_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('rfc', models.CharField(db_column='RFC', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El RFC debe tener 13 caracteres.', regex='^.{13}$')])),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='empresa',
        ),
    ]
