# Generated by Django 5.1.2 on 2024-11-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPieza',
            fields=[
                ('id_add_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_piezas', models.IntegerField(blank=True, null=True)),
                ('descripcion_pieza', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'add_pieza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioPiezas',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_stock_piezas', models.IntegerField()),
                ('fecha_entrada', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario_piezas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Piezas',
            fields=[
                ('id_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pieza', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'piezas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProveedorPiezas',
            fields=[
                ('id_proveedor_piezas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, db_column='Nombre_empresa', max_length=100, null=True)),
                ('rfc', models.CharField(blank=True, db_column='RFC', max_length=40, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('tipo_moneda_pago', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'proveedor_piezas',
                'managed': False,
            },
        ),
    ]
