# Generated by Django 5.1.2 on 2024-11-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallemaquinariaEmpresa',
            fields=[
                ('id_detalle_maquinaria_empresa', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detallemaquinaria_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantenimientos',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'mantenimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id_maquinaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_maquinaria', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'maquinaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PiezasMantenimiento',
            fields=[
                ('ind_pieza_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_usada', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'piezas_mantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id_tipo_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_mantenimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('fecha_servicio', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_mantenimiento',
                'managed': False,
            },
        ),
    ]
