# Generated by Django 5.1.2 on 2024-11-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidomaterno_empleado', models.CharField(blank=True, db_column='apellidoMaterno_empleado', max_length=50, null=True)),
                ('apellidopaterno_empleado', models.CharField(blank=True, db_column='apellidoPaterno_empleado', max_length=50, null=True)),
                ('telefono', models.FloatField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
    ]
