# Generated by Django 5.1.4 on 2024-12-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Programmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("nickname", models.CharField(max_length=50)),
                ("age", models.PositiveSmallIntegerField()),
                ("is_activate", models.BooleanField(default=True)),
            ],
        ),
    ]
